### ISSUE TITLE
UI suggestions

### ISSUE THREAD

**Issue by skttl** [dawoe/umbraco-tour-editor#1]
What a great package idea!

I have some suggestions for the UI, to make it easier to use.

I think you should add the tours to the tree, so it's easier to navigate to and from a specific tour, and, then use the interface from nested content to control the tour steps.

Right now, you can't go back from a tour or tour step. I know this is very much WIP, so maybe you have already thought of this :)

![image](https://user-images.githubusercontent.com/3726467/36368250-ab1addb6-1556-11e8-8463-d829fe8743c9.png)

**Comment by dawoe** [comment]
Hi @skttl 

For various reasons listing the tours in the tree did not work.

However the latest beta has better UI flow. Maybe you can test it ? It's still a WIP at the momet
