### ISSUE TITLE
Umbraco 7.8 view errors

### ISSUE THREAD

**Issue by Mantus667** [dawoe/umbraco-tour-editor#17]
Installed the package inside a 7.8.0 instance.
When trying to edit a tour it can't find some views as the url is wrong.

![image](https://user-images.githubusercontent.com/1239113/39268095-2139da32-48cf-11e8-99ac-eac3b26eacb9.png)

**Comment by dawoe** [comment]
Hi David,

Are you running chrome 66 perhaps ? If so you need to upgrade to the latest 7.8.x version. Chrome 66 update broke a internal js method of Umbraco. https://umbraco.com/blog/chrome-66-causing-errors-on-some-umbraco-sites/

Dave

**Comment by Mantus667** [comment]
Indeed that was the issue
